Fixes #1: Write README to explain the purpose of the repository and how to use the script.
ai-cfia/report-automation pull request #2
Opened 2024-04-19 19:21 UTC by MaxenceGui

Fixes #1

- [x] Write the README to explain the purpose, the scope and the usage of the repository

2024-04-22 19:03 UTC, amirardalan9473 approved these changes

2024-04-23 20:07 UTC, SonOfLope approved these changes

2024-04-24 15:23 UTC, ibrahim-kabir requested changes
the repository file_for_report doesn't exist in the workspace causing an error
```cmd
  File "C:\Users\Ibrahim Kabir\acia\report-automation\report_script.py", line 211, in <module>
    main()
  File "C:\Users\Ibrahim Kabir\acia\report-automation\report_script.py", line 207, in main
    start_programm()
  File "C:\Users\Ibrahim Kabir\acia\report-automation\report_script.py", line 200, in start_programm
    create_file_entry_frame("file_for_report")
  File "C:\Users\Ibrahim Kabir\acia\report-automation\report_script.py", line 168, in create_file_entry_frame
    files = os.listdir(directory)
```

2024-04-24 15:35 UTC, ibrahim-kabir reviewed
Tkinter is generating an error about the module tabulate. Add it to the requirements.txt
```cmd
$ python report_script.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Ibrahim Kabir\acia\report-automation\.venv\Lib\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ibrahim Kabir\.pyenv\pyenv-win\versions\3.11.1\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tabulate'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ibrahim Kabir\.pyenv\pyenv-win\versions\3.11.1\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Ibrahim Kabir\acia\report-automation\report_script.py", line 132, in generate_report
    generate_markdown("REPORT_TEMPLATE.md", f"{keys['date']}_report.md", "file_for_report", **keys)
  File "C:\Users\Ibrahim Kabir\acia\report-automation\report_script.py", line 25, in generate_markdown
    charts, markdown_table = prepare_file_for_report(directory)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ibrahim Kabir\acia\report-automation\report_script.py", line 64, in prepare_file_for_report
    table = df_sorted.to_markdown(index=False)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ibrahim Kabir\acia\report-automation\.venv\Lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ibrahim Kabir\acia\report-automation\.venv\Lib\site-packages\pandas\core\frame.py", line 2983, in to_markdown
    tabulate = import_optional_dependency("tabulate")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ibrahim Kabir\acia\report-automation\.venv\Lib\site-packages\pandas\compat\_optional.py", line 138, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'tabulate'.  Use pip or conda to install tabulate.
Traceback (most recent call last):
  File "C:\Users\Ibrahim Kabir\acia\report-automation\report_script.py", line 211, in <module>
    main()
  File "C:\Users\Ibrahim Kabir\acia\report-automation\report_script.py", line 207, in main
    start_programm()
  File "C:\Users\Ibrahim Kabir\acia\report-automation\report_script.py", line 204, in start_programm
    root.mainloop()
  File "C:\Users\Ibrahim Kabir\.pyenv\pyenv-win\versions\3.11.1\Lib\tkinter\__init__.py", line 1485, in mainloop
    self.tk.mainloop(n)
```

2024-04-24 15:35 UTC, elwoujdi commented on README.md
> +   (your name), `Iteration Date`, and the `Milestones` you are working on.
Add the format of iteration date (screenshot from github)

2024-04-24 15:35 UTC, elwoujdi commented on README.md
> +1. The right component allows you to add `.tsv` files. - Those files usually are
Add instructions by a gif, video, or bullet points

2024-04-24 15:46 UTC, ibrahim-kabir reviewed
![image](https://github.com/ai-cfia/report-automation/assets/117961703/1fc36e25-137c-4120-bb77-feda975b3935)

Replace to the project, not only Nachet.

![image](https://github.com/ai-cfia/report-automation/assets/117961703/4ce6e9cb-6761-473c-933b-bf644fc99333)

Add maybe a checkbox to enable or disable milestones

Finally maybe add an output folder

2024-04-24 23:56 UTC, MaxenceGui commented on README.md
> +1. The right component allows you to add `.tsv` files. - Those files usually are
Done

2024-04-24 23:56 UTC, MaxenceGui commented on README.md
> +   (your name), `Iteration Date`, and the `Milestones` you are working on.
Done

2024-04-24 23:56 UTC, MaxenceGui commented
I think I fixed and implement everything you point out @ibrahim-kabir

2024-04-25 20:17 UTC, ibrahim-kabir approved these changes
LGTM

2024-04-25 20:19 UTC, merged